Fix path finding for windows environments
blomqma/next-rest-framework pull request #41
Opened 2023-05-11 22:46 UTC by almontasser

Windows uses `\` instead of `/` for path Seperators. This fixes index routes not found on windows files system

2023-05-16 17:44 UTC, blomqma commented
Awesome, some of the tests are still failing. Happy to merge this after the CI is green. You can run the tests locally with `pnpm test`, I can also help if you need assistance with fixing the test failures.

2023-05-16 17:44 UTC, blomqma requested changes
Awesome, some of the tests are still failing. Happy to merge this after the CI is green. You can run the tests locally with `pnpm test`, I can also help if you need assistance with fixing the test failures.

2023-05-16 18:26 UTC, almontasser commented
The tests seem to be failing even before I've changed a thing 🤔

2023-05-16 21:32 UTC, almontasser commented
Still needs tests for tags feature.

![image](https://github.com/blomqma/next-rest-framework/assets/19656179/bded3774-ce28-4ce5-9bdd-f5d9b1acac7f)

2023-05-18 22:03 UTC, blomqma approved these changes
LGTM, thanks for the contribution!

2023-05-18 22:04 UTC, merged